version: '3.8'
 
services:
  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root_password  
      MYSQL_DATABASE: app_db             
      MYSQL_USER: user               
      MYSQL_PASSWORD: app_password       
    ports:
      - "3307:3307"
    volumes:
      - db_data:/var/lib/mysql
 
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    depends_on:
      - db
    environment:
      DATABASE_URL: mysql+pymysql://user:app_password@db/app_db
 
  adminer:
    image: adminer
    restart: always
    ports:
      - "8080:8080"
 
volumes:
  db_data: